<?php

/**
 * @file
 * Contains custom_solr_search.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_solr_search module.
    case 'help.page.custom_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Solr Search') . '</p>';
      return $output;

    default:
  }
}

