<?php

/**
 * @param \Drupal\Core\Entity\EntityInterface $node
 */
//function nvli_shorten_node_presave(Drupal\Core\Entity\EntityInterface $node) {
//  if (($node->getType() == 'resource') && (empty($node->get('field_text_plain_single_1')))) {
//    $nid = $node->id();
//    // @todo Make base url dynamic.
//    $source_url = 'http://dev-nvli.iitb.ac.in//node/' . $nid;
//    $short_url = \Drupal::service('nvli_shorten.manager')
//      ->generateShortUrl($source_url);
//    $node->set('field_text_plain_single_1', $short_url->shortUrl);
//  }
//}